env:
  node: true
  es2021: true

extends: 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  camelcase: 0
  no-plusplus: 0
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
